#!/usr/bin/env bash
set -eo pipefail


if [[ "$OSTYPE" = "darwin"* ]]; then
  export $(grep -v '^#' .env | xargs -0);
else
  export $(grep -v '^#' .env | xargs -d '\n');
fi

# cf https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac/24572274#24572274
function getDir {
  if [[ "$OSTYPE" = "darwin"* ]]; then
    perl -MCwd -e 'print Cwd::abs_path shift' "$CLIENT_DIR"
  else
    readlink -f "$CLIENT_DIR";
  fi
}

APP_DIR=$(getDir "$CLIENT_DIR");

function attachOpenPgp {
  cp node_modules/openpgp/dist/openpgp* "$1/.";
}

function run {
  local dir="$APP_DIR/$1/dist";

  rm -rf "$dir";

  if [[ "$1" = 'dist' ]]; then
      npx parcel build src/index.html --public-url . --out-dir "$dir";
      attachOpenPgp "$dir";
  else
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir";
    fi

    attachOpenPgp "$dir";
    npx parcel src/index.html --public-url . --out-dir "$dir";
  fi
}

if [ "$1" = 'dev' ]; then
    run "static"
fi

if [ "$1" = 'dist' ]; then
    run "dist"
fi
